In [1]:
import numpy as np

In [2]:
y = np.array([[110],[140],[180],[190]])
x = np.array([[180,150,1],[150,175,1],[170,165,1],[185,210,1]])
print (x) 
print (y) 

[[180 150   1]
 [150 175   1]
 [170 165   1]
 [185 210   1]]
[[110]
 [140]
 [180]
 [190]]


In [3]:
theta_1 = np.dot(x.T,x)
theta_2 = np.linalg.inv(theta_1)
theta = np.dot(theta_2,np.dot(x.T,y))

In [4]:
# mle theta
theta

array([[  0.11595569],
       [  1.06057035],
       [-50.45722366]])

In [5]:
summation_hat = np.dot( np.subtract(y , np.dot(x,theta) )  , np.subtract(y , np.dot(x,theta) ).T  )

In [6]:
summation_hat 

array([[ 380.26378754,  244.45529199, -697.15027716,   72.43119763],
       [ 244.45529199,  157.14983056, -448.16803531,   46.56291276],
       [-697.15027716, -448.16803531, 1278.10884145, -132.79052898],
       [  72.43119763,   46.56291276, -132.79052898,   13.7964186 ]])

In [7]:
'''
for i in range(4):
    for j in range(4):
        if i != j:
            summation_hat[i][j] = 0
'''

'\nfor i in range(4):\n    for j in range(4):\n        if i != j:\n            summation_hat[i][j] = 0\n'

In [8]:
summation_hat

array([[ 380.26378754,  244.45529199, -697.15027716,   72.43119763],
       [ 244.45529199,  157.14983056, -448.16803531,   46.56291276],
       [-697.15027716, -448.16803531, 1278.10884145, -132.79052898],
       [  72.43119763,   46.56291276, -132.79052898,   13.7964186 ]])

In [9]:
x_new = np.array([[175,170,1]])

In [10]:
y_hat = np.dot( x_new , theta )

In [11]:
y_hat

array([[150.13198209]])

In [12]:
first

NameError: name 'first' is not defined

In [13]:
first.T

NameError: name 'first' is not defined

In [14]:
## variance for y_hat distribution

first =  np.dot(np.linalg.inv(np.dot(x.T,x)),x.T)

second = np.dot(np.dot(first,summation_hat),first.T)

variance = np.dot(x_new,np.dot(second,x_new.T))

In [15]:
variance[0][0]**(1/2)

1.5975905202812795e-07

In [16]:
print("[", y_hat[0][0]-1.96*variance[0][0]**(1/2),",",y_hat[0][0]+1.96*variance[0][0]**(1/2),"]")

[ 150.13198177502318 , 150.13198240127866 ]


In [17]:
#2.7(d)

print((theta[0][0]**2))
print(((second[0][0])))
print((theta[0][0]**2)/(second[0][0]))

0.01344572244402108
-2.1666828609636614e-18
-6205671668091247.0


In [18]:
print((theta[1][0]**2))
print((second[1][1]))
print((theta[1][0]**2)/(second[1][1]))

1.1248094697737132
1.248933392533277e-17
9.006160588694032e+16


In [19]:
(theta[2]**2)/((second[2][2]))

array([-4.1477189e+15])

In [20]:
z = x/2

In [21]:
z

array([[ 90. ,  75. ,   0.5],
       [ 75. ,  87.5,   0.5],
       [ 85. ,  82.5,   0.5],
       [ 92.5, 105. ,   0.5]])

In [22]:
np.linalg.inv(np.dot(x.T,x))

array([[ 1.47065755e-03, -2.07400424e-04, -2.15555032e-01],
       [-2.07400424e-04,  5.42069291e-04, -5.93448032e-02],
       [-2.15555032e-01, -5.93448032e-02,  4.75491398e+01]])

In [23]:
summation_hat

array([[ 380.26378754,  244.45529199, -697.15027716,   72.43119763],
       [ 244.45529199,  157.14983056, -448.16803531,   46.56291276],
       [-697.15027716, -448.16803531, 1278.10884145, -132.79052898],
       [  72.43119763,   46.56291276, -132.79052898,   13.7964186 ]])

In [24]:
variance

array([[2.55229547e-14]])

In [25]:
np.dot(x_new,np.dot(np.linalg.inv(np.dot(x.T,np.dot(np.linalg.inv(summation_hat),x))),x_new.T))

array([[2.06812587e-14]])

In [26]:
second

array([[-2.16668286e-18, -1.80842030e-17,  4.20722874e-15],
       [-1.26955787e-17,  1.24893339e-17, -2.23670103e-16],
       [ 2.85509589e-15,  3.68037165e-16, -6.13814841e-13]])

In [27]:
np.dot(lx.T,np.dot(np.linalg.inv(summation_hat),x))

NameError: name 'lx' is not defined

In [28]:
np.linalg.inv(summation_hat)

array([[ 8.06308527e+12,  6.49235437e+12,  1.11134311e+13,
         4.27238804e+13],
       [-0.00000000e+00, -3.51843721e+13, -1.23373772e+13,
        -0.00000000e+00],
       [ 4.39804651e+12, -8.79609302e+12, -4.34092902e+12,
        -3.51843721e+13],
       [-0.00000000e+00, -0.00000000e+00, -5.84883068e+13,
        -5.62949953e+14]])

In [29]:
second

array([[-2.16668286e-18, -1.80842030e-17,  4.20722874e-15],
       [-1.26955787e-17,  1.24893339e-17, -2.23670103e-16],
       [ 2.85509589e-15,  3.68037165e-16, -6.13814841e-13]])

In [30]:
a = [110,140,180,190]

In [31]:
(np.var(a))**(1/2)

32.01562118716424

In [32]:
1

1

# Version 2

In [33]:
y = np.array([[110],[140],[180],[190]])
x = np.array([[180,150,1],[150,175,1],[170,165,1],[185,210,1]])
print (x) 
print (y) 

[[180 150   1]
 [150 175   1]
 [170 165   1]
 [185 210   1]]
[[110]
 [140]
 [180]
 [190]]


In [34]:
theta_1 = np.dot(x.T,x)
theta_2 = np.linalg.inv(theta_1)
theta = np.dot(theta_2,np.dot(x.T,y))

In [35]:
np.dot(x_new,theta)

array([[150.13198209]])

In [40]:
np.subtract(y , np.dot(x,theta))

array([[-19.50035352],
       [-12.53594155],
       [ 35.75064813],
       [ -3.71435305]])

In [37]:
sigma_2 = np.dot( np.subtract(y , np.dot(x,theta) ).T  , np.subtract(y , np.dot(x,theta) )  )/4

In [38]:
sigma_2

array([[457.32971954]])

In [41]:
sigma = sigma_2[0][0]**(1/2)

In [42]:
sigma_2

array([[457.32971954]])

In [80]:
(sigma_2*np.dot(np.dot(x_new,np.linalg.inv(np.dot(x.T,x))),x_new.T))

array([[133.54502062]])

In [81]:
stddev = (sigma_2*np.dot(np.dot(x_new,np.linalg.inv(np.dot(x.T,x))),x_new.T))**(1/2)

In [82]:
print(np.dot(x_new,theta)-1.96*stddev,np.dot(x_new,theta)+1.96*stddev)

[[127.48189266]] [[172.78207152]]


In [83]:
cov_matrix = sigma_2 * np.linalg.inv(np.dot(x.T,x))

In [84]:
cov_matrix

array([[ 6.72575407e-01, -9.48503778e-02, -9.85797222e+01],
       [-9.48503778e-02,  2.47904397e-01, -2.71401422e+01],
       [-9.85797222e+01, -2.71401422e+01,  2.17456348e+04]])

In [86]:
theta[0][0]**2 / cov_matrix[0][0]

0.019991397713069774

In [88]:
theta[1][0]**2 / cov_matrix[1][1]

4.53727116188877

In [92]:
from scipy import stats

In [98]:
stats.chi2.cdf(theta[1][0]**2 / cov_matrix[1][1], 1, loc=0, scale=1)

0.9668355789584154